import { ServiceDefinition } from "./types";

export const SERVICES: ServiceDefinition[] = [
  {
    slug: "fraud",
    title: "Fraud First Aid",
    short: "Financial fraud — first hour",
    problem: "Money left my account and I don't know who to call first.",
    persona: "Asha, 42, UPI user, mid-range Android",
    badge: "Flagship · Judged journey",
    color: "#FF5A1F",
    intents: ["Money left my account", "Card charged I didn't do", "UPI scam"],
    workflow: [
      { id: "contain", title: "Contain", kind: "form" },
      { id: "transaction", title: "Transaction", kind: "form" },
      { id: "evidence", title: "Evidence", kind: "evidence" },
      { id: "verify", title: "Verify", kind: "ai_review" },
      { id: "statement", title: "Statement", kind: "form" },
      { id: "review", title: "Review", kind: "consent" },
      { id: "submitted", title: "Submitted", kind: "result" },
    ],
    mockArtifact: "IND-FRAUD-2026-88471 · Bank alert + Portal ack",
  },
  {
    slug: "irctc",
    title: "IRCTC — Get Me Home",
    short: "Disrupted train journey",
    problem: "My train is WL 47, will I reach for my interview?",
    persona: "Graduate, Tier-2 city, next-day interview",
    badge: "IRCTC · Alternative routing",
    color: "#0E7C3E",
    intents: ["WL not clearing", "Find alternative", "Refund"],
    workflow: [
      { id: "search", title: "Search", kind: "form" },
      { id: "alternatives", title: "Alternatives", kind: "ai_review" },
      { id: "passenger", title: "Passenger", kind: "form" },
      { id: "review", title: "Review", kind: "consent" },
      { id: "ticket", title: "Ticket", kind: "result" },
    ],
    mockArtifact: "PNR 482-7719033 · Alternatives compared",
  },
  {
    slug: "income-tax",
    title: "Income Tax — File With Confidence",
    short: "Salaried ITR filing",
    problem: "Which regime saves me money? Did I miss a deduction?",
    persona: "Salaried, 29, Form 16 + interest income",
    badge: "e-Filing · Regime compare",
    color: "#1D4ED8",
    intents: ["Which ITR to file", "Regime check", "AIS mismatch"],
    workflow: [
      { id: "income", title: "Income", kind: "form" },
      { id: "reconcile", title: "Reconcile", kind: "ai_review" },
      { id: "compare", title: "Compare", kind: "form" },
      { id: "review", title: "Review", kind: "consent" },
      { id: "filed", title: "Filed", kind: "result" },
    ],
    mockArtifact: "ACK-ITR-88261 · Old vs New regime explained",
  },
  {
    slug: "cpgrams",
    title: "CPGRAMS — Be Heard",
    short: "Grievance routing",
    problem: "I know what happened, but which department owns it?",
    persona: "Citizen with water/electricity grievance",
    badge: "Grievance · Routing",
    color: "#7C3AED",
    intents: ["Grievance story", "Find department", "Track + appeal"],
    workflow: [
      { id: "story", title: "Story", kind: "form" },
      { id: "route", title: "Route", kind: "ai_review" },
      { id: "evidence", title: "Evidence", kind: "evidence" },
      { id: "review", title: "Review", kind: "consent" },
      { id: "track", title: "Track", kind: "result" },
    ],
    mockArtifact: "CPGRAMS/2026/11482 · Routed with reason",
  },
  {
    slug: "gst",
    title: "GST — Obligation Cockpit",
    short: "Small business filing",
    problem: "What must I pay and fix this month?",
    persona: "Kirana + online sales, monthly filer",
    badge: "GST · Impact-ordered",
    color: "#B45309",
    intents: ["Upload invoices", "Fix mismatch", "Pay + file"],
    workflow: [
      { id: "invoices", title: "Invoices", kind: "evidence" },
      { id: "mismatch", title: "Mismatch", kind: "ai_review" },
      { id: "liability", title: "Liability", kind: "form" },
      { id: "review", title: "Review", kind: "consent" },
      { id: "receipt", title: "Receipt", kind: "result" },
    ],
    mockArtifact: "GST RET 3B Aug 2026 · Mismatch resolved",
  },
  {
    slug: "epfo",
    title: "EPFO — Job Change Resolver",
    short: "PF continuity",
    problem: "I switched jobs, balances don't match, transfer stuck.",
    persona: "Employee, 2 employers in 2 years",
    badge: "EPFO · Timeline health",
    color: "#0F766E",
    intents: ["Transfer PF", "Missing exit date", "Balance split"],
    workflow: [
      { id: "timeline", title: "Timeline", kind: "form" },
      { id: "detect", title: "Detect", kind: "ai_review" },
      { id: "transfer", title: "Transfer", kind: "form" },
      { id: "review", title: "Review", kind: "consent" },
      { id: "status", title: "Status", kind: "result" },
    ],
    mockArtifact: "TRN-EPFO-7731 · Consolidated passbook",
  },
  {
    slug: "mca",
    title: "MCA — Company by Event",
    short: "Private Ltd compliance",
    problem: "We added a director — what to file, who signs, when?",
    persona: "Pvt Ltd founder, 2 directors",
    badge: "MCA · Event graph",
    color: "#111827",
    intents: ["Add director", "Annual filing", "Incorporation"],
    workflow: [
      { id: "event", title: "Event", kind: "form" },
      { id: "requirements", title: "Requirements", kind: "ai_review" },
      { id: "form", title: "Prepare", kind: "form" },
      { id: "sign", title: "Sign & Pay", kind: "consent" },
      { id: "srn", title: "SRN", kind: "result" },
    ],
    mockArtifact: "SRN T98765432 · Dependency graph closed",
  },
  {
    slug: "umang",
    title: "UMANG — Life Event Router",
    short: "One plan, many departments",
    problem: "My father retired — which 6 services, in what order?",
    persona: "Son helping retired parent",
    badge: "UMANG · Intent plan",
    color: "#BE123C",
    intents: ["Father retired", "I moved states", "Child born"],
    workflow: [
      { id: "event", title: "Life event", kind: "form" },
      { id: "plan", title: "Plan", kind: "ai_review" },
      { id: "complete", title: "Complete one", kind: "form" },
      { id: "track", title: "Unified status", kind: "result" },
    ],
    mockArtifact: "UMANG Plan 3/6 · Reused profile with consent",
  },
  {
    slug: "parivahan",
    title: "Parivahan — Sold My Car",
    short: "Vehicle transfer",
    problem: "I sold my car — who does what to transfer ownership safely?",
    persona: "Seller + buyer, different RTO states",
    badge: "Parivahan · Buyer/seller split",
    color: "#0369A1",
    intents: ["Transfer ownership", "RC lost", "DL renewal"],
    workflow: [
      { id: "vehicle", title: "Vehicle", kind: "form" },
      { id: "sale", title: "Sale split", kind: "form" },
      { id: "documents", title: "Documents", kind: "ai_review" },
      { id: "appointment", title: "Pay + Appointment", kind: "consent" },
      { id: "proof", title: "Proof", kind: "result" },
    ],
    mockArtifact: "APPL-TRANS-4491 · Seller/buyer timeline",
  },
  {
    slug: "rti",
    title: "RTI — Ask Right",
    short: "Valid RTI request",
    problem: "Is this RTI or grievance? Which authority? How to ask so it's answerable?",
    persona: "Citizen seeking municipal records",
    badge: "RTI · Authority + drafting",
    color: "#854D0E",
    intents: ["Draft RTI", "Find authority", "First appeal"],
    workflow: [
      { id: "need", title: "Need", kind: "form" },
      { id: "check", title: "RTI check", kind: "ai_review" },
      { id: "authority", title: "Authority", kind: "form" },
      { id: "draft", title: "Draft", kind: "form" },
      { id: "receipt", title: "Receipt", kind: "result" },
    ],
    mockArtifact: "RTI/2026/88201 · 3 record questions scoped",
  },
];

export const getService = (slug: string) => SERVICES.find(s => s.slug === slug);
