"use client";
import Link from "next/link";
import { ArrowRight, Camera, Check, Clock, MapPin, ShieldCheck } from "lucide-react";
import { Card, CardContent } from "@/components/ui/Card";

export default function Home() {
  return (
    <div>
      <section className="mx-auto max-w-[1160px] px-4 sm:px-6 pt-10 pb-8">
        <div className="grid lg:grid-cols-[1.05fr_0.95fr] gap-8 items-start">
          <div>
            <div className="text-xs font-semibold tracking-[0.18em] text-red-700">BUILD WHAT MOVES INDIA · FOOD SAFETY</div>
            <h1 className="mt-3 max-w-[650px] text-[42px] sm:text-[64px] font-semibold tracking-[-0.055em] leading-[0.9]">A food-safety complaint should not disappear into a form.</h1>
            <p className="mt-5 max-w-[590px] text-[17px] leading-7 text-zinc-700">Send one clear report. We organise the evidence, identify the responsible food-safety office and keep every next step visible—from inspection to laboratory result or corrective action.</p>
            <div className="mt-6 flex flex-wrap gap-3"><Link href="/food" className="inline-flex items-center gap-2 rounded-full bg-[#DC2626] px-5 py-3 text-sm font-semibold text-white hover:bg-[#B91C1C]">Report a food-safety risk <ArrowRight size={16} /></Link></div>
            <div className="mt-6 grid sm:grid-cols-3 gap-3 max-w-[640px]"><div className="border-l-2 border-red-600 pl-3"><div className="text-2xl font-semibold">1 photo</div><div className="text-xs text-zinc-500">evidence before paperwork</div></div><div className="border-l-2 border-red-600 pl-3"><div className="text-2xl font-semibold">1 owner</div><div className="text-xs text-zinc-500">inspection responsibility visible</div></div><div className="border-l-2 border-red-600 pl-3"><div className="text-2xl font-semibold">72h plan</div><div className="text-xs text-zinc-500">targeted action timeline, not a promise</div></div></div>
          </div>
          <Card className="overflow-hidden border-red-200"><div className="bg-[#DC2626] text-white px-5 py-4 flex items-center justify-between"><span className="flex items-center gap-2 font-semibold"><ShieldCheck size={18} /> What happens after you report</span><span className="text-xs text-white/75">one clear path</span></div><CardContent className="p-5"><div className="rounded-2xl border border-zinc-200 bg-zinc-50 p-4"><div className="flex items-center gap-2 text-xs font-semibold tracking-widest text-zinc-500"><Camera size={14} /> THREE STEPS</div><div className="mt-4 space-y-3">{["Share a photo, place and the problem", "The responsible food-safety team reviews and assigns the case", "You can follow inspection, sample testing and corrective action"].map((step, i) => <div key={step} className="flex gap-3 text-sm"><span className="h-6 w-6 shrink-0 grid place-items-center rounded-full bg-zinc-900 text-white text-xs">{i + 1}</span><span>{step}</span></div>)}</div></div><div className="mt-4 rounded-2xl border border-amber-200 bg-amber-50 p-4 text-sm text-amber-950"><b>Your safety comes first:</b> never confront a food business or take a photo if it puts you at risk.</div></CardContent></Card>
        </div>
      </section>
      <section className="mx-auto max-w-[1160px] px-4 sm:px-6 pb-12"><div className="flex items-end justify-between gap-4"><div><div className="text-xs font-semibold tracking-widest text-zinc-500">WHY THIS PROBLEM</div><h2 className="mt-2 text-2xl font-semibold tracking-tight">The complaint is not the outcome.</h2></div><Link href="/disclosures" className="text-sm font-medium underline">How the service works →</Link></div><div className="mt-5 grid md:grid-cols-3 gap-4"><Card><CardContent className="p-5"><MapPin className="text-red-600" size={20} /><h3 className="mt-3 font-semibold">Location is hard to translate</h3><p className="mt-2 text-sm leading-6 text-zinc-600">A citizen knows the shop, stall or delivery order—not the ward, jurisdiction or inspecting office.</p></CardContent></Card><Card><CardContent className="p-5"><Clock className="text-red-600" size={20} /><h3 className="mt-3 font-semibold">Evidence loses its context</h3><p className="mt-2 text-sm leading-6 text-zinc-600">Photos without time, product, location or a clear allegation are harder to triage and act on.</p></CardContent></Card><Card><CardContent className="p-5"><Check className="text-red-600" size={20} /><h3 className="mt-3 font-semibold">“Resolved” is not visible enough</h3><p className="mt-2 text-sm leading-6 text-zinc-600">Citizens need a case reference, owner, next checkpoint and outcome—not a silent submit button.</p></CardContent></Card></div></section>
      <section className="mx-auto max-w-[1160px] px-4 sm:px-6 pb-16"><div className="rounded-[24px] bg-zinc-900 text-white p-6 sm:p-8"><div className="text-xs font-semibold tracking-widest text-white/60">FROM REPORT TO ACTION</div><div className="mt-2 flex flex-wrap items-end justify-between gap-4"><h2 className="text-2xl font-semibold">The case does not stop at submission</h2><Link href="/food" className="rounded-full bg-white text-zinc-900 px-4 py-2 text-sm font-semibold">Start report</Link></div><div className="mt-5 grid md:grid-cols-4 gap-3">{[["01","Organise","Evidence, product and place"],["02","Prioritise","Risk and exposure"],["03","Act","Inspection, sample or recall"],["04","Prove","Outcome and correction"]].map(([n,t,d]) => <div key={n} className="rounded-2xl border border-white/15 bg-white/10 p-4"><div className="text-xs text-white/60">{n}</div><div className="mt-2 text-sm font-semibold">{t}</div><div className="mt-1 text-xs text-white/65">{d}</div></div>)}</div></div></section>
    </div>
  );
}
